### ISSUE TITLE
I downloaded the program Google auth

### ISSUE THREAD

**Issue by bmazak** [richard-green/LCGoogleApps#2]
How to install it?  Dont understand what to do. Dont want to stop using Google verification codes on Android. Want to use this app also but the program is not executable.  How to compile or what? For my Desktop.

**Comment by richard-green** [comment]
Hi,
I've uploaded the latest version here: http://rdgreen.eu/downloads/LCGoogleApps.exe
This program requires .NET Framework 3.5 to run
Hope that helps,
Richard

**Comment by bmazak** [comment]
I’m at a loss! What are you talking about?

**Comment by bmazak** [comment]
Could you please tell me what this is in regards too?

**Comment by richard-green** [comment]
Hi,
On GitHub you raised an issue that you couldn't install the LCGoogleApps program, so I sent you a link to a compiled version that you can download and run on your desktop.
When you run the program you should get a little padlock icon in your system tray and you can add your google authenticator account to that by following the readme here: https://github.com/richard-green/LCGoogleApps/
Thanks,
Richard

**Comment by bmazak** [comment]
OH this is about that. Sorry I couldn’t connect LC and Authenticator.

Well Thank you very much.
